export const CHANGE_MENU_STATE = 'CHANGE_MENU_STATE';
export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';

